[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "gcc", "tesseract", "postgresql"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"